name: Run workflow when app is hit

on:
  issues:
    types: [opened]

jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
    - name: Run my app's action
      uses: workflow/actions@v1
      with:
        issue-number: ${{ github.event.issue.number }}
