name: Run workflow when app is hit

on:
  issues:
    types: [opened]

jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/checkout@v2
       with:
         repository: 
      
    -    uses: ./
    - name: Run my app's action
      uses: SiyaaJhawar/workflow@main
      with:
        issue-number: ${{ github.event.issue.number }}

    
